CREATE SCHEMA BRH; 

USE BRH; 

CREATE TABLE CEP (

CEP VARCHAR (20) NOT NULL,
BAIRRO VARCHAR (50) NOT NULL,
CIADADE VARCHAR (50) NOT NULL,
ESTADOR VARCHAR (50) NOT NULL,
CONSTRAINT PK_CEP PRIMARY KEY (CEP)

);


CREATE TABLE PESSOAL (

CPF VARCHAR (20) NOT NULL,
CEP VARCHAR (20) NOT NULL,
NOME VARCHAR (20) NOT NULL,
EMAIL_PESSOAL VARCHAR (50) NOT NULL, 
LOGRADOURO VARCHAR (100) NOT NULL,
COMPLEMENTO VARCHAR (100) NOT NULL, 
CONSTRAINT PK_CPF PRIMARY KEY (CPF),
FOREIGN KEY (CEP) REFERENCES CEP (CEP)
ON DELETE CASCADE
ON UPDATE CASCADE

);

CREATE TABLE DEPARTAMENTO_SUPERIOR (
DEPARTAMENTO_SUPERIOR VARCHAR (10) NOT NULL,
CONSTRAINT PK_DEPARTAMENTO_SUPERIOR PRIMARY KEY ( DEPARTAMENTO_SUPERIOR)
);


CREATE TABLE DEPARTAMENTO (

SIGLA VARCHAR (10) NOT NULL,
NOME VARCHAR (50) NOT NULL,
CHEFE VARCHAR (50) NOT NULL, 
DEPARTAMENTO_SUPERIOR VARCHAR (50) NOT NULL, 
CONSTRAINT PK_SIGLA PRIMARY KEY (SIGLA),
FOREIGN KEY ( DEPARTAMENTO_SUPERIOR) REFERENCES DEPARTAMENTO_SUPERIOR (DEPARTAMENTO_SUPERIOR)
ON DELETE CASCADE
ON UPDATE CASCADE
);

CREATE TABLE COLABORADOR (

MATRICULA VARCHAR (10) NOT NULL,
CPF VARCHAR (20) NOT NULL,
EMAIL_CORPORATIVO VARCHAR (50) NOT NULL,
SALARIO DECIMAL (7,2) NOT NULL,
DEPARTAMENTO VARCHAR (10) NOT NULL,
CONSTRAINT PK_MATRICULA PRIMARY KEY (MATRICULA),
FOREIGN KEY (CPF) REFERENCES PESSOAL (CPF)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY (DEPARTAMENTO) REFERENCES DEPARTAMENTO (SIGLA)
ON DELETE CASCADE
ON UPDATE CASCADE
);

CREATE TABLE DEPENDENTE (

CPF_DEPENDENTE VARCHAR (20) NOT NULL,
MATRICULA VARCHAR (10) NOT NULL, 
NOME VARCHAR (50) NOT NULL,
DATA_NASCIMENTO DATE NOT NULL,
PARENTESCO VARCHAR (20) NOT NULL,
CONSTRAINT PK_CPF_DEPENDENTE PRIMARY KEY (CPF_DEPENDENTE),
FOREIGN KEY (MATRICULA) REFERENCES COLABORADOR (MATRICULA)
ON DELETE CASCADE
ON UPDATE CASCADE
);


CREATE TABLE TELEFONE_COLABORADOR (

TELEFONE_1 VARCHAR (20) NOT NULL,
TELEFONE_2 VARCHAR (20) NOT NULL,
MATRICULA VARCHAR (10) NOT NULL,
CONSTRAINT PK_TELEFONE_1 PRIMARY KEY (TELEFONE_1),
FOREIGN KEY (MATRICULA) REFERENCES COLABORADOR (MATRICULA)
ON DELETE CASCADE
ON UPDATE CASCADE

);


CREATE TABLE PROJETO (

ID VARCHAR (10) NOT NULL,
NOME VARCHAR (50) NOT NULL,
MATRICULA VARCHAR (10) NOT NULL,
INICIO DATE NOT NULL,
LIMITE DATE NOT NULL,
CONSTRAINT PK_ID PRIMARY KEY (ID),
FOREIGN KEY (MATRICULA) REFERENCES COLABORADOR ( MATRICULA)
ON DELETE CASCADE
ON UPDATE CASCADE

);

CREATE TABLE PAPEL (

ID VARCHAR (10) NOT NULL,
NOME VARCHAR (50) NOT NULL,
CONSTRAINT PK_ID PRIMARY KEY (ID)

);

CREATE TABLE ATRIBUICAO (

MATRICULA VARCHAR (10) NOT NULL,
ID VARCHAR (10) NOT NULL,
PAPEL VARCHAR (150) NOT NULL,
FOREIGN KEY ( MATRICULA) REFERENCES COLABORADOR (MATRICULA)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY (ID) REFERENCES PROJETO (ID)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY (PAPEL) REFERENCES PAPEL (ID)
ON DELETE CASCADE
ON UPDATE CASCADE
);

